version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
    ports:
      - '9200:9200'
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - /user/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2
    container_name: kibana
    environment:
      - node.name=kibana
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  drom_parser:
    image: parser
    volumes:
      - ./data:/data
    container_name: drom_parser
    command: python ./parser/parser.py
    network_mode: host
    build:
      context: parser
      dockerfile: Dockerfile

  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.2
    container_name: logstash
    volumes:
      - ./elk/logstash.conf:/usr/share/logstash/logstash.conf
      - ./data/cars.csv:/usr/share/logstash/data/cars.csv
    restart: always
    depends_on:
      - elasticsearch
    command: bash -c "logstash-plugin install logstash-output-elasticsearch && bin/logstash -f logstash.conf"
    networks:
      - elastic

volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge
